---
- name: Hello World Playbook
  hosts: localhost
  tasks:
  - name: Print Hello World message
    ansible.builtin.debug:
      msg: "Hello, World!"
  - name: Install python
    ansible.builtin.apt:
      name:
      - python
      - python3-pip
      state: present
    when: ansible_os_family =="RedHat"
  - name: Install http
    ansible.builtin.apt:
      name: httpd
      state: present
    when: ansible_os_family =="RedHat"
