---
- name: Hello World Playbook
  hosts: localhost
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
  - name: Install http
    ansible.builtin.dnf:
      name: httpd
      state: present
