---
- name: Hello World Playbook
  hosts: localhost
  vars:
    ansible_python_interpreter: /usr/libexec/platform-python
  tasks:
  - name: Install http
    ansible.builtin.yum:
      name: httpd
      state: present
